# Generated by Django 2.0.1 on 2018-01-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('infoAdicional', models.CharField(max_length=500)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Oferta', max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('descuento', models.IntegerField()),
                ('limite', models.DateField()),
                ('diaSemana', models.IntegerField()),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now=True)),
                ('mesa', models.IntegerField()),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tamaño', models.CharField(blank=True, choices=[('M', 'Medio'), ('P', 'Pequeño'), ('G', 'Grande')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/tipos')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='platillo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Tipo'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='platillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Platillo'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Tipo'),
        ),
        migrations.AddField(
            model_name='detallesorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Orden'),
        ),
        migrations.AddField(
            model_name='detallesorden',
            name='platillo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Platillo'),
        ),
        migrations.AddField(
            model_name='detallescombo',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Platillo'),
        ),
    ]
