# Generated by Django 2.0.1 on 2018-02-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180201_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('G', 'Grande'), ('P', 'Pequeño'), ('M', 'Medio')], default='M', max_length=1),
        ),
    ]
